### ISSUE TITLE
Soap Action inválida

### ISSUE THREAD

**Issue by rodovalho** [leotada/PyNFe#25]
Oi Pessoal,

Estou me juntando ao projeto de vocês. 

Porém, num primeiro teste, usando o código de "Consulta Cadastro" disponível no Wiki do Github, estou me deparando com o seguinte problema:

```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <soap:Fault>
      <soap:Code>
        <soap:Value>soap:Sender</soap:Value>
      </soap:Code>
      <soap:Reason>
        <soap:Text xml:lang="en">System.Web.Services.Protocols.SoapException: Unable to handle request without a valid action parameter. Please supply a valid soap action.
   at System.Web.Services.Protocols.Soap12ServerProtocolHelper.RouteRequest()
   at System.Web.Services.Protocols.SoapServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocol.SetContext(Type type, HttpContext context, HttpRequest request, HttpResponse response)
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean&amp; abortProcessing)</soap:Text>
      </soap:Reason>
      <soap:Detail/>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>

```
Aqui está o XML gerado pela pyNFE:
```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soap:Body>
    <nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4">
      <ConsCad xmlns="http://www.portalfiscal.inf.br/nfe" versao="2.00">
        <infCons>
          <xServ>CONS-CAD</xServ>
          <UF>RS</UF>
          <CNPJ>999999999999</CNPJ>
        </infCons>
      </ConsCad>
    </nfeDadosMsg>
  </soap:Body>
</soap:Envelope>

```
Só para constar. Estou no RJ e usando os servidores do RS. Estou no python3. Aqui está meu pip freeze:
```
asn1crypto==0.22.0
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
cryptography==1.9
decorator==4.1.2
defusedxml==0.5.0
eight==0.4.2
future==0.16.0
idna==2.6
ipython==6.2.0
ipython-genutils==0.2.0
jedi==0.10.2
lxml==3.8.0
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
pycparser==2.18
Pygments==2.2.0
PyNFe==0.2
pyOpenSSL==17.3.0
python-dateutil==2.6.1
PyXB==1.2.6
requests==2.18.4
signxml==2.4.0
simplegeneric==0.8.1
six==1.10.0
suds-jurko==0.6
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7

```
Desde já obrigado.

**Comment by juniortada** [comment]
Qual versão vc está testando a master 4.00 ou o branch 3.10?

**Comment by rodovalho** [comment]
Aparentemente nem uma nem outra. :/

```
In [2]: pynfe.get_version()
Out[2]: '0.4'

```

**Comment by juniortada** [comment]
A versão 4.00 ainda não tem url para consulta cadastro, como foi modificado o soap e o ssl não irá funcionar. Para utilizar a consulta de cadastro desinstale versão 4.00 e instale o branch 3.10 ex:

pip3 install https://github.com/leotada/PyNFe/archive/3.10.zip

**Comment by juniortada** [comment]
É versão da nota fiscal, não versão do PyNFe.

**Comment by rodovalho** [comment]
Está funcionando agora. POrém, agora estou com o seguinte erro. Como disse anteriormente, estou no RJ porém, estou ciente de que devo utilizar os servidores do RS, correto?

Segue meu código:
```
from pynfe.processamento.comunicacao import ComunicacaoSefaz
 
certificado = "XXXXXX.pfx"
senha = 'XXXXX'
uf = 'RS'
homologacao = True
 
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
xml = con.consulta_cadastro('nfe','XXXXXXX')
print (xml.text)

```


```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Header>
    <nfeCabecMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2">
      <cUF>43</cUF>
      <versaoDados>2.00</versaoDados>
    </nfeCabecMsg>
  </soap:Header>
  <soap:Body>
    <consultaCadastro2Result xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2">
      <retConsCad xmlns="http://www.portalfiscal.inf.br/nfe" versao="2.00">
        <infCons>
          <verAplic>RSb20170704091239</verAplic>
          <cStat>259</cStat>
          <xMotivo>Rejeicao: CNPJ da consulta nao cadastrado como contribuinte na UF</xMotivo>
          <UF>RS</UF>
          <CNPJ>XXXXXXXXXXX</CNPJ>
          <dhCons>2017-10-06T15:54:01</dhCons>
          <cUF>43</cUF>
        </infCons>
      </retConsCad>
    </consultaCadastro2Result>
  </soap:Body>
</soap:Envelope>
```

**Comment by juniortada** [comment]
RJ utiliza o SVRS para emitir, cancelar, etc. Para consulta cadastro, as UF que tem consulta cadastro são apenas AC, RN, PB e SC. As demais UF utilizam um sistema próprio. RJ só encontrei site e não webservice para consulta.

http://www4.fazenda.rj.gov.br/sefaz-dfe-consulta-credenciamento/paginas/consulta.faces

Caso consiga mais informações junto a SEFAZ RJ sobre webservice de consulta cadastro, me notifica que eu atualizo o PyNFe.
