### ISSUE TITLE
Erro ao Gerar NFC-e para o Estado do Rio de Janeiro

### ISSUE THREAD

**Issue by rodovalho** [leotada/PyNFe#26]
Utilizando o exemplo do wiki (https://github.com/leotada/PyNFe/wiki/Emiss%C3%A3o-de-NFCe) estou obtendo o seguinte erro:
```
Traceback (most recent call last):
  File "nfce-example.py", line 117, in <module>
    xml_com_qrcode = SerializacaoQrcode().gerar_qrcode(token, csc, xml)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/pynfe/processamento/serializacao.py", line 674, in gerar_qrcode
    qrcode = NFCE[uf.upper()]['HOMOLOGACAO'] + NFCE[uf.upper()]['QR'] + url
KeyError: 'HOMOLOGACAO'
```
Indo lá ver (webservices.py) como está definida a estrutura da "NFCE", encontro o RJ em branco.:
```
NFCE = {
(...)
 'RJ': {
    'STATUS': '',
    'AUTORIZACAO': '',
    'RECIBO': '',
    'CHAVE': '',
    'INUTILIZACAO': '',
    'EVENTOS': '',
    'QR': ''
},
(...)
}
```
Obrigado

**Comment by juniortada** [comment]
Rodrigo, RJ utiliza SVRS para NFC-e também. A única url que irá utilizar é QR. Atualizei a url e adicionei RJ na lista das UF SVRS. Atualiza o PyNFe e testa novamente.

**Comment by rodovalho** [comment]
Oi Junior,

O erro persiste. Se você notar, a mensagem de erro menciona a inexistência da Key "HOMOLOGACAO". 

Apenas para evitar qualquer problema, estou colocando em anexo, um resumo do meu código atual. Estou apenas omitindo os detalhes dos dados da empresa e do cliente:

```
from pynfe.processamento.comunicacao import ComunicacaoSefaz
from pynfe.entidades.cliente import Cliente
from pynfe.entidades.emitente import Emitente
from pynfe.entidades.notafiscal import NotaFiscal
from pynfe.entidades.fonte_dados import _fonte_dados
from pynfe.processamento.serializacao import SerializacaoXML, SerializacaoQrcode
from pynfe.processamento.assinatura import AssinaturaA1
from pynfe.utils.flags import CODIGO_BRASIL
from decimal import Decimal
import datetime

certificado = "XXXXXXX.pfx"
senha = 'XXXXXX'
uf = 'RS' 
homologacao = True

# emitente
emitente = Emitente(
    razao_social='XXXXXXXXXXXXXXXX EIRELI - ME',
    nome_fantasia='XXXXXXXXX',
    cnpj='XXXXXXX',           # cnpj apenas números
    codigo_de_regime_tributario='1', # 1 para simples nacional ou 3 para normal
    inscricao_estadual='XXXXXXXX', # numero de IE da empresa
    inscricao_municipal='XXXXXXX',
    cnae_fiscal='5611201',           # cnae apenas números
    endereco_logradouro='XXXXXXXXXXXXXXX',
    endereco_numero='X',
    endereco_bairro='XXXXXXXXXX',
    endereco_municipio='Niteroi',
    endereco_uf='RJ',
    endereco_cep='XXXXXXXXXXXX',
    endereco_pais=CODIGO_BRASIL
)

# cliente
cliente = Cliente(
    razao_social='XXXXXXXXXXXXXXX',
    tipo_documento='CPF',           #CPF ou CNPJ
    email='XXXXXXXXXXXXXX@gmail.com',
    numero_documento='XXXXXXXXXXXX', # numero do cpf ou cnpj
    indicador_ie=9,                 # 9=Não contribuinte 
    endereco_logradouro='XXXXXXXXXXXXXX',
    endereco_numero='XX',
    endereco_complemento='XXXXXXXXX',
    endereco_bairro='XXXXX',
    endereco_municipio='Niteroi',
    endereco_uf='RJ',
    endereco_cep='XXXXXXX',
    endereco_pais=CODIGO_BRASIL,
    endereco_telefone='XXXXXXXX',
)

# Nota Fiscal
nota_fiscal = NotaFiscal(
   emitente=emitente,
   cliente=cliente,
   uf='RJ',
   natureza_operacao='VENDA', # venda, compra, transferência, devolução, etc
   forma_pagamento=0,         # 0=Pagamento à vista; 1=Pagamento a prazo; 2=Outros.
   tipo_pagamento=1,
   modelo=65,                 # 55=NF-e; 65=NFC-e
   serie='1',
   numero_nf='001',           # Número do Documento Fiscal.
   data_emissao=datetime.datetime.now(),
   data_saida_entrada=datetime.datetime.now(),
   tipo_documento=1,          # 0=entrada; 1=saida
   municipio='3303302',       # Código IBGE do Município 
   tipo_impressao_danfe=4,    # 0=Sem geração de DANFE;1=DANFE normal, Retrato;2=DANFE normal Paisagem;3=DANFE Simplificado;4=DANFE NFC-e;
   forma_emissao='1',         # 1=Emissão normal (não em contingência);
   cliente_final=1,           # 0=Normal;1=Consumidor final;
   indicador_destino=1,
   indicador_presencial=1,
   finalidade_emissao='1',    # 1=NF-e normal;2=NF-e complementar;3=NF-e de ajuste;4=Devolução de mercadoria.
   processo_emissao='0',      #0=Emissão de NF-e com aplicativo do contribuinte;
   transporte_modalidade_frete=1,
   informacoes_adicionais_interesse_fisco='Mensagem complementar',
   totais_tributos_aproximado=Decimal('21.06'),
)

# Produto
nota_fiscal.adicionar_produto_servico(
    codigo='000328',                           # id do produto
    descricao='Vários Produtos',
    ncm='99999999',
    cfop='5102',
    unidade_comercial='UN',
    quantidade_comercial=Decimal('12'),        # 12 unidades
    valor_unitario_comercial=Decimal('9.75'),  # preço unitário
    valor_total_bruto=Decimal('117.00'),       # preço total
    unidade_tributavel='UN',
    quantidade_tributavel=Decimal('12'),
    valor_unitario_tributavel=Decimal('9.75'),
    ind_total=1,
    icms_modalidade='102',
    icms_origem=0,
    icms_csosn='400',
    pis_modalidade='07',
    cofins_modalidade='07',
    valor_tributos_aprox='21.06'
    )

# serialização
serializador = SerializacaoXML(_fonte_dados, homologacao=homologacao)
nfce = serializador.exportar()

# assinatura
a1 = AssinaturaA1(certificado, senha)
xml = a1.assinar(nfce)

# token de homologacao
token = '000001'

# csc de homologação
csc = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

# gera e adiciona o qrcode no xml NT2015/003
xml_com_qrcode = SerializacaoQrcode().gerar_qrcode(token, csc, xml)

# envio
con = ComunicacaoSefaz(uf, certificado, senha, homologacao)
envio = con.autorizacao(modelo='nfce', nota_fiscal=xml_com_qrcode)

# em caso de sucesso o retorno será o xml autorizado 
if envio[0] == 0:
    print('SUCESSO')
    print (envio[1].text)
# em caso de erro o retorno será o xml de resposta da SEFAZ
else:
    print('ERRO')
    print (envio[1].text)
    print (envio[2].text)

```

**Comment by juniortada** [comment]
Seu código está errado, na UF vc deve declarar RJ e não RS, o PyNFe é que vai tratar de procurar a URL de SVRS para RJ. Para todos os efeitos, vc está emitindo para UF do emitente.

**Comment by rodovalho** [comment]
Ok. 

Trocando a linha
`uf = 'RS'`
para 
`uf = 'RJ'`

Olha o traceback agora:
`Traceback (most recent call last):
  File "nfce-example.py", line 121, in <module>
    envio = con.autorizacao(modelo='nfce', nota_fiscal=xml_com_qrcode)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 46, in autorizacao
    retorno = self._post(url, xml)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 441, in _post
    raise e
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/pynfe/processamento/comunicacao.py", line 437, in _post
    result = requests.post(url, xml, headers=self._post_header(), cert=chave_cert, verify=False, timeout=120)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/home/rodrigo/Workspace/.virtualenvs/pyNFE/lib/python3.5/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
`

**Comment by juniortada** [comment]
Atualiza seu PyNFe da versão 3.10, a URL já foi corrigida!
